server:
  port: 8083

grpc:
  server:
    port: ${GRPC_PORT:9083}
  client:
    rule-engine:
      address: ${BIDDING_ENGINE_GRPC_ADDRESS:static://localhost:9082}
      negotiation-type: plaintext

spring:
  application:
    name: workflow-engine
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://name:password@localhost:8888}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  cloud:
    bus:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,refresh
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
