services:
  kafka:
    image: bitnami/kafka:3.8
    container_name: omnibus-kafka
    environment:
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:29092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:29092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_KRAFT_CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
      ALLOW_PLAINTEXT_LISTENER: "yes"
    ports:
      - "29092:29092"

  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    container_name: omnibus-keycloak
    command:
      - start-dev
      - --import-realm
    environment:
      KEYCLOAK_ADMIN: kcadmin
      KEYCLOAK_ADMIN_PASSWORD: kcadmin
      KC_METRICS_ENABLED: "true"
      KC_HEALTH_ENABLED: "true"
    volumes:
      - ./infra/keycloak/realm-omnibus.json:/opt/keycloak/data/import/realm-omnibus.json:ro
    ports:
      - "9090:8080"

  bidding-engine:
    build:
      context: ./bidding-engine
    container_name: omnibus-bidding-engine
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    volumes:
      - ./bidding-engine/managed-rules:/app/managed-rules
    depends_on:
      - kafka
    ports:
      - "8080:8080"

  bff-nest:
    build:
      context: ./bff-nest
    container_name: omnibus-bff
    environment:
      BACKEND_BASE_URL: http://bidding-engine:8080
      KEYCLOAK_URL: http://localhost:9090
      KEYCLOAK_INTERNAL_URL: http://keycloak:8080
      KEYCLOAK_REALM: omnibus
      KEYCLOAK_CLIENT_ID: omnibus-frontend
      PORT: 3000
    depends_on:
      - keycloak
      - bidding-engine
    ports:
      - "3000:3000"

  frontend-angular:
    build:
      context: ./frontend-angular
    container_name: omnibus-frontend
    depends_on:
      - bff-nest
    ports:
      - "4200:80"

  prometheus:
    image: prom/prometheus:v2.54.1
    container_name: omnibus-prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - bidding-engine
      - kafka
      - keycloak
    ports:
      - "9091:9090"
