spring:
  application:
    name: cassandra-projection-service

  cloud:
    stream:
      bindings:
        orders-in-0:
          destination: orders.events
          group: cassandra-projection-group
          content-type: application/json

      kafka:
        binder:
          brokers: kafka:9092

  data:
    cassandra:
      contact-points: cassandra
      port: 9042
      keyspace-name: orders
      local-datacenter: datacenter1

management:
  endpoints:
    web:
      exposure:
        include: health,metrics
