CREATE TABLE post (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(400) NOT NULL,
  content VARCHAR(2000) NULL,
  created TIMESTAMP
);

CREATE TABLE comment (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  post_id BIGINT,
  content VARCHAR(2000) NULL,
  created TIMESTAMP
);

ALTER TABLE comment
  ADD CONSTRAINT comment_post_id
  FOREIGN KEY (post_id) REFERENCES post (id)
