server {
    listen 80;
    server_name _;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    # =========================
    # FRONTEND
    # =========================
    location / {
        proxy_pass http://frontend-angular:80;
    }

    # =========================
    # BFF LAYER
    # =========================
    location /api/ {
        proxy_pass http://bff-nest:3000/api/;
    }

    # =========================
    # BIDDING ENGINE
    # =========================
    location = /swagger-ui.html {
        proxy_pass http://bidding-engine:8081/swagger-ui.html;
    }

    location /swagger-ui/ {
        proxy_pass http://bidding-engine:8081/swagger-ui/;
    }

    location = /api-docs {
        proxy_pass http://bidding-engine:8081/api-docs;
    }

    location /actuator/ {
        proxy_pass http://bidding-engine:8081/actuator/;
    }

    # =========================
    # WORKFLOW ORCHESTRATOR
    # =========================
    location = /workflow/swagger-ui.html {
        proxy_pass http://workflow-orchestrator:8082/swagger-ui.html;
    }

    location /workflow/swagger-ui/ {
        proxy_pass http://workflow-orchestrator:8082/swagger-ui/;
    }

    location = /workflow/api-docs {
        proxy_pass http://workflow-orchestrator:8082/api-docs;
    }

    location /workflow/actuator/ {
        rewrite ^/workflow/actuator/(.*)$ /actuator/$1 break;
        proxy_pass http://workflow-orchestrator:8082;
    }

    # =========================
    # EVENT ARCHIVE
    # =========================
    location /archive/actuator/ {
        proxy_pass http://event-archive:8083/actuator/;
    }

    # =========================
    # AUTH (KEYCLOAK)
    # =========================
    location /keycloak/ {
        rewrite ^/keycloak/(.*)$ /$1 break;
        proxy_pass http://keycloak:8080/;
    }

    # =========================
    # OBSERVABILITY
    # =========================
    location /prometheus/ {
        proxy_pass http://prometheus:9090/;
    }
}