server {
  listen 80;

  # =========================
  # FRONTENDS
  # =========================

  location /angular/ {
    proxy_pass http://host.docker.internal:4200/;
  }

  location /react/ {
    proxy_pass http://host.docker.internal:5173/;
  }

  # =========================
  # BACKEND (BFF)
  # =========================

  location /api/ {
    proxy_pass http://host.docker.internal:3000/;
  }

  # =========================
  # INFRA UIs
  # =========================

  location /grafana/ {
    proxy_pass http://grafana:3000/;
  }

  location /keycloak/ {
    proxy_pass http://keycloak:8080/;
  }

  location /kafka/ {
    proxy_pass http://kafka-ui:8080/;
  }

  # =========================
  # DASHBOARD (STATIC)
  # =========================

  location / {
    root /usr/share/nginx/html;
    index index.html;
  }
}