server:
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/writeonly/omnibus
          default-label: main
          clone-on-start: true
          search-paths:
            - services/core/config-server/config
    stream:
      default-binder: kafka

  security:
    user:
      name: name
      password: password

management:
  endpoints:
    web:
      exposure:
        include: health,info
