services:

  config-server:
    build:
      context: .
      dockerfile: core/config-server/Dockerfile
    container_name: config-server
    ports:
      - "8888:8888"
    environment:
      CONFIG_ENV: local
      CONFIG_REPO_LOCATION: file:/workspace/config
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    volumes:
      - ./core/config-server/config:/workspace/config
    networks:
      - omnibus

  auth-server:
    build:
      context: .
      dockerfile: core/auth-server/Dockerfile
    container_name: auth-server
    ports:
      - "9000:9000"
    depends_on:
      - config-server
    environment:
      CONFIG_SERVER_URL: http://name:password@config-server:8888
      DB_URL: jdbc:postgresql://postgres:5432/auth_db
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      AUTH_ISSUER: http://auth-server:9000
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - omnibus

  api-gateway:
    build:
      context: .
      dockerfile: core/api-gateway/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - config-server
      - auth-server
      - rule-engine
      - workflow-engine
    environment:
      CONFIG_SERVER_URL: http://name:password@config-server:8888
      AUTH_SERVER_URL: http://auth-server:9000
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      RULE_ENGINE_GRPC_URI: h2c://rule-engine:9081
      WORKFLOW_ENGINE_GRPC_URI: h2c://workflow-engine:9082
    networks:
      - omnibus

  rule-engine:
    build:
      context: .
      dockerfile: core/rule-engine/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - config-server
      - auth-server
    environment:
      CONFIG_SERVER_URL: http://name:password@config-server:8888
      AUTH_SERVER_URL: http://auth-server:9000
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - omnibus

  workflow-engine:
    build:
      context: .
      dockerfile: core/workflow-engine/Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - config-server
      - auth-server
      - rule-engine
    environment:
      CONFIG_SERVER_URL: http://name:password@config-server:8888
      AUTH_SERVER_URL: http://auth-server:9000
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      BIDDING_ENGINE_GRPC_ADDRESS: static://rule-engine:9081
    networks:
      - omnibus

networks:
  omnibus:
    name: omnibus
