services:

  config-server:
    build:
      context: .
      dockerfile: core/config-server/Dockerfile
    container_name: config-server
    ports:
      - "8888:8888"
    environment:
      JAVA_TOOL_OPTIONS: "-Xms128m -Xmx256m"
      CONFIG_ENV: local
      CONFIG_REPO_LOCATION: file:/workspace/config
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    volumes:
      - ./core/config-server/config:/workspace/config
    networks:
      - omnibus

  eureka-server:
    build:
      context: .
      dockerfile: core/eureka-server/Dockerfile
    container_name: eureka-server
    ports:
      - "8761:8761"
    depends_on:
      - config-server
    environment:
      JAVA_TOOL_OPTIONS: "-Xms128m -Xmx256m"
      CONFIG_SERVER_URL: http://name:password@config-server:8888
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - omnibus

  auth-server:
    build:
      context: .
      dockerfile: core/auth-server/Dockerfile
    container_name: auth-server
    ports:
      - "9000:9000"
    depends_on:
      - config-server
      - eureka-server
    environment:
      JAVA_TOOL_OPTIONS: "-Xms128m -Xmx256m"
      CONFIG_SERVER_URL: http://name:password@config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
      DB_URL: jdbc:postgresql://postgres:5432/auth_db
      POSTGRES_DB: auth_db
      DB_USERNAME: omnibus
      DB_PASSWORD: omnibus
      AUTH_ISSUER: http://auth-server:9000
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - omnibus

  api-gateway:
    build:
      context: .
      dockerfile: core/api-gateway/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - config-server
      - auth-server
      - eureka-server
      - rule-engine
      - workflow-engine
    environment:
      JAVA_TOOL_OPTIONS: "-Xms128m -Xmx256m"
      CONFIG_SERVER_URL: http://name:password@config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
      AUTH_SERVER_URL: http://auth-server:9000
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      RULE_ENGINE_GRPC_URI: h2c://rule-engine:9081
      WORKFLOW_ENGINE_GRPC_URI: h2c://workflow-engine:9082
    networks:
      - omnibus

  audit-service:
    build:
      context: .
      dockerfile: core/audit-service/Dockerfile
    container_name: audit-service
    ports:
      - "8081:8081"
    depends_on:
      - config-server
      - eureka-server
      - auth-server
    environment:
      JAVA_TOOL_OPTIONS: "-Xms128m -Xmx256m"
      CONFIG_SERVER_URL: http://name:password@config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka

      KAFKA_BOOTSTRAP_SERVERS: kafka:9092

      DB_URL: jdbc:postgresql://postgres:5432/audit_db
      DB_USERNAME: omnibus
      DB_PASSWORD: omnibus
      POSTGRES_DB: audit_db

      AUTH_SERVER_URL: http://auth-server:9000
    networks:
      - omnibus

  user-service:
    build:
      context: .
      dockerfile: core/user-service/Dockerfile
    container_name: user-service
    ports:
      - "8082:8082"
    depends_on:
      - config-server
      - eureka-server
      - auth-server
    environment:
      JAVA_TOOL_OPTIONS: "-Xms128m -Xmx256m"
      CONFIG_SERVER_URL: http://name:password@config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
      AUTH_SERVER_URL: http://auth-server:9000
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092

      # jeśli używasz DB w user-service:
      DB_URL: jdbc:postgresql://postgres:5432/user_db
      DB_USERNAME: omnibus
      DB_PASSWORD: omnibus
      POSTGRES_DB: user_db
    networks:
      - omnibus

  rule-engine:
    build:
      context: .
      dockerfile: core/rule-engine/Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - config-server
      - auth-server
      - eureka-server
    environment:
      JAVA_TOOL_OPTIONS: "-Xms128m -Xmx256m"
      CONFIG_SERVER_URL: http://name:password@config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
      AUTH_SERVER_URL: http://auth-server:9000
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - omnibus

  workflow-engine:
    build:
      context: .
      dockerfile: core/workflow-engine/Dockerfile
    ports:
      - "8084:8084"
    depends_on:
      - config-server
      - auth-server
      - eureka-server
      - rule-engine
    environment:
      JAVA_TOOL_OPTIONS: "-Xms128m -Xmx256m"
      CONFIG_SERVER_URL: http://name:password@config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
      AUTH_SERVER_URL: http://auth-server:9000
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      BIDDING_ENGINE_GRPC_ADDRESS: static://rule-engine:9081
    networks:
      - omnibus

networks:
  omnibus:
    name: omnibus
 