services:

  config-server:
    build:
      context: .
      dockerfile: core/config-server/Dockerfile
    container_name: config-server
    ports:
      - "8888:8888"
    environment:
      CONFIG_ENV: local
    volumes:
      - ./core/config-server/config:/workspace/config

  api-gateway:
    build:
      context: .
      dockerfile: core/api-gateway/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - config-server
      - rule-engine
      - workflow-engine
    networks: [omnibus]

  rule-engine:
    build:
      context: .
      dockerfile: core/rule-engine/Dockerfile
    ports:
      - "8081:8081"
    depends_on: 
      - config-server
    networks: [omnibus]

  workflow-engine:
    build:
      context: .
      dockerfile: core/workflow-engine/Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - config-server
      - rule-engine
    networks: [omnibus]

  event-archive:
    profiles:
      - legacy
    build:
      context: .
      dockerfile: legacy/services/event-archive/Dockerfile
    networks: [omnibus]

  outbox-relay-service:
    profiles:
      - legacy
    build:
      context: .
      dockerfile: legacy/outbox-relay-service/Dockerfile
    networks: [omnibus]

  cassandra-projection-service:
    profiles:
      - legacy
    build:
      context: .
      dockerfile: legacy/cassandra-projection-service/Dockerfile
    networks: [omnibus]

networks:
  omnibus:
