spring:
  application:
    name: bidding-engine

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true

omnibus:
  rules:
    storage-path: managed-rules
