server:
  port: 8080
  http2:
    enabled: true

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: rule-service-grpc
              uri: "${RULE_ENGINE_GRPC_URI:lb:h2c://rule-service}"
              predicates:
                - Path=/omnibus.v1.BiddingService/**

            - id: workflow-service-grpc
              uri: "${WORKFLOW_ENGINE_GRPC_URI:lb:h2c://workflow-service}"
              predicates:
                - Path=/omnibus.v1.WorkflowService/**

            - id: user-service-grpc
              uri: "${USER_SERVICE_GRPC_URI:lb:h2c://user-service}"
              predicates:
                - Path=/omnibus.v1.UserService/**

            - id: modulith-user-http
              uri: "${MODULITH_HTTP_URI:lb://modulith}"
              predicates:
                - Path=/api/user/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_ISSUER_URI:http://keycloak:9000/realms/omnibus}

logging:
  file:
    name: logs/app.log
  level:
    root: INFO
