management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics,refresh
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true

logging:
  file:
    name: logs/app.log
  level:
    root: INFO

spring:
  cloud:
    bus:
      enabled: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      auto-offset-reset: earliest
    producer:
      acks: all
  jackson:
    default-property-inclusion: non_null
  jmx:
    enabled: false

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
