server:
  port: 8081

spring:
  application:
    name: modulith
  cloud:
    gateway:
      grpc:
        enabled: true
  config:
    import: "configserver:${CONFIG_SERVER_URL:http://name:password@localhost:8888}"

grpc:
  client:
    userService:
      address: ${USER_SERVICE_GRPC_URI:static://localhost:9082}
      negotiation-type: plaintext
