server:
  port: 8081

spring:
  application:
    name: modulith
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  cloud:
    gateway:
      grpc:
        enabled: true
  config:
    import: "configserver:${CONFIG_SERVER_URL:http://name:password@localhost:8888}"

grpc:
  client:
    userService:
      address: ${USER_SERVICE_GRPC_URI:static://localhost:9083}
      negotiation-type: plaintext

    rule-service:
      address: static://localhost:9086
      negotiationType: plaintext

    workflow-service:
      address: static://localhost:9087
      negotiationType: plaintext
