server:
  port: 8080

grpc:
  server:
    port: ${GRPC_PORT:9080}
  client:
    bidding-engine:
      address: ${BIDDING_ENGINE_GRPC_ADDRESS:static://localhost:9081}
      negotiation-type: plaintext
    workflow-orchestrator:
      address: ${WORKFLOW_ORCHESTRATOR_GRPC_ADDRESS:static://localhost:9082}
      negotiation-type: plaintext

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8180/realms/omnibus

  cloud:
    gateway:
      server:
        webflux:
          routes:

            - id: bidding-engine
              uri: http://bidding-engine:8081
              predicates:
                - Path=/internal/bidding/**

            - id: workflow-orchestrator
              uri: http://workflow-orchestrator:8082
              predicates:
                - Path=/internal/workflow/**

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics
