server:
  port: 8080

grpc:
  server:
    port: ${GRPC_PORT:9080}
  client:
    rule-engine:
      address: ${RULE_ENGINE_GRPC_ADDRESS:static://localhost:9081}
      negotiation-type: plaintext
    workflow-engine:
      address: ${WORKFLOW_ENGINE_GRPC_ADDRESS:static://localhost:9082}
      negotiation-type: plaintext

spring:
  config:
    import: optional:configserver:http://localhost:8888

  cloud:
    gateway:
      server:
        webflux:
          routes:

            - id: rule-engine
              uri: http://rule-engine:8081
              predicates:
                - Path=/internal/rule/**

            - id: workflow-engine
              uri: http://workflow-engine:8082
              predicates:
                - Path=/internal/workflow/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8180/realms/omnibus

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics
