server:
  port: 8080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8180/realms/omnibus

  cloud:
    gateway:
      server:
        webflux:
          routes:

            - id: bff
              uri: http://bff-nest:3000
              predicates:
                - Path=/api/**

            - id: bidding-engine
              uri: http://bidding-engine:8081
              predicates:
                - Path=/internal/bidding/**

            - id: workflow
              uri: http://workflow-orchestrator:8082
              predicates:
                - Path=/internal/workflow/**

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics
