server:
  port: 8080
  http2:
    enabled: true

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: rule-engine-grpc
              uri: "${RULE_ENGINE_GRPC_URI:h2c://rule-engine:9081}"
              predicates:
                - Path=/omnibus.v1.BiddingService/**

            - id: workflow-engine-grpc
              uri: "${WORKFLOW_ENGINE_GRPC_URI:h2c://workflow-engine:9082}"
              predicates:
                - Path=/omnibus.v1.WorkflowService/**
