server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: rule-engine
          uri: http://rule-engine:8081
          predicates:
            - Path=/api/rule/**

        - id: workflow-engine
          uri: http://workflow-engine:8082
          predicates:
            - Path=/api/workflow/**
