server:
  port: 8080
  http2:
    enabled: true

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: rule-engine-grpc
              uri: "${RULE_ENGINE_GRPC_URI:lb:h2c://rule-engine}"
              predicates:
                - Path=/omnibus.v1.BiddingService/**

            - id: workflow-engine-grpc
              uri: "${WORKFLOW_ENGINE_GRPC_URI:lb:h2c://workflow-engine}"
              predicates:
                - Path=/omnibus.v1.WorkflowService/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_ISSUER_URI:http://keycloak:8180/realms/omnibus}
