server:
  port: 8082

grpc:
  server:
    port: ${GRPC_PORT:9082}

eureka:
  instance:
    non-secure-port: ${GRPC_PORT:9082}
    metadata-map:
      grpc.port: ${GRPC_PORT:9082}

logging:
  file:
    name: logs/app.log
  level:
    root: INFO

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://postgres:5432/user_db}
    username: ${DB_USERNAME:omnibus}
    password: ${DB_PASSWORD:omnibus}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: user-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

logging:
  level:
    pl.writeonly.omnibus.user: DEBUG
