
config:
	./gradlew :config-server:bootRun

eureka:
	./gradlew :eureka-server:bootRun

auth:
	./gradlew :auth-server:bootRun	

api:
	./gradlew :api-gateway:bootRun

audit:
	./gradlew :audit-service:bootRun

user:
	./gradlew :user-service:bootRun

rule:
	./gradlew :rule-service:bootRun

workflow:
	./gradlew :workflow-service:bootRun
