
config:
	./gradlew :config-server:bootRun

eureka:
	./gradlew :eureka-server:bootRun

api:
	./gradlew :api-gateway:bootRun

modulith:
	./gradlew :modulith:bootRun

auth:
	./gradlew :auth-service:bootRun

user:
	./gradlew :user-service:bootRun

notification:
	./gradlew :notification-service:bootRun

audit:
	./gradlew :audit-service:bootRun

rule:
	./gradlew :rule-service:bootRun

workflow:
	./gradlew :workflow-service:bootRun
